data:
  columns:
    - company_id
    - timestamp_utc
    - energy_demand_mw
  target_column: energy_demand_mw
  temporal_column: timestamp_utc
  lookback: 14
  offset_year: 2025
  step: 4
model:
  k: 5
  lightgbm:
    base_params:
      objective: regression
      metric: rmse
      early_stopping_rounds: 50
      verbosity: -1
      n_jobs: -1
    hyperparams:
      - n_estimators
      - max_depth
      - learning_rate
      - num_leaves
      - min_data_in_leaf
  xgboost:
    base_params:
      objective: reg:squarederror
      eval_metric: rmse
      early_stopping_rounds: 50
      n_jobs: -1
    hyperparams:
      - n_estimators
      - max_depth
      - learning_rate
      - min_child_weight
      - reg_alpha
